config/routes.rb
Rails.application.routes.draw do
  

  resources :photos
  resources :homes
  root 'home#index'
  devise_for :users
  get 'near_homes' => 'homes#show_near_by_homes', :as=> ""
  get 'filter_homes' => 'homes#show_filter', :as=> ""
  get 'home/photos/:id' => 'photos#homephoto', :as=> ""
  get 'admin' => 'admin#index', :as=> "admin"

  

end

app/models/home.rb
class Home < ActiveRecord::Base

include ActiveModel::Serialization


	belongs_to :user

	has_many :photos , dependent: :destroy
	accepts_nested_attributes_for :photos


	validates_presence_of :address
	validates_length_of :photos, maximum: 4 
	validates_presence_of :rate
	validates :rate, :numericality => { :greater_than_or_equal_to => 0 }
	geocoded_by :address,
		:latitude => :lat, :longitude => :long
	after_validation :geocode


	
def self.search(rate, locat,   pets,   internet,  tv , laundry , heater , parking , air_cond)
		scope=  Home.all
		scope= scope.near(locat, 20) if locat!=""
		scope= scope.where(rate: rate) if rate 

		scope= scope.where(pets: pets) if pets!="false"

		scope= scope.where(internet: internet) if internet!="false"
		scope= scope.where(tv: tv) if tv!="false"
		scope= scope.where(laundry: laundry) if laundry!="false"
		scope= scope.where(heater: heater) if heater!="false"
		scope= scope.where(parking: parking) if parking!="false"
		scope= scope.where(air_cond: air_cond) if air_cond!="false"

		scope

	end

end

app/models/photo.rb
class Photo < ActiveRecord::Base
	mount_uploader :image, ImageUploader
	belongs_to :home 
	validates_associated :home
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :homes, dependent: :destroy

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	before_filter :is_admin?
	def index	
		@homes = Home.all.order( 'created_at DESC' )
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ActionController::Serialization
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def is_admin?
    if user_signed_in?
      if current_user.admin
        true
      else
        flash[:notice] = "You are not an admin"
        redirect_to :root
      end
    else
      redirect_to :root
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@homes = Home.all
  	if Home.count > 0
	  	@min_price_home = Home.order(:rate).first.rate
	  	@max_price_home = Home.order(:rate).last.rate
  	end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	before_action :authenticate_user! ,except: [:index ,:show_near_by_homes, :show_filter ,:show]
  before_filter :is_admin?, only: [:destroy, :edit]

	def index
		respond_to do |format|
      homes = Home.all
      format.json { render json: homes.map{|f| HomesSerializer.new(f)}.to_json }
    end
	end

	def new
		@homes = Home.new
	end

  def edit
    @home = Home.find(params[:id])
  end

  def update
    @home = Home.find(params[:id])
    respond_to do |format|
      if @home.update(home_params)
        if params[:photo]
         params[:photo]['image'].each do |a|
          @photo = @homes.photos.create!(:image => a, :home_id => @homes.id)
        end
       end
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { render :index, status: :updated, location: @home }
      else
        format.html { render :edit }
        format.json { render json: @home.errors, status: :unprocessable_entity }   
      end
    end
  end

	def create
		@homes = Home.new(home_params)
		@homes.user_id = current_user.id
		respond_to do |format|
      if params[:photo]
        if @homes.save
          params[:photo]['image'].each do |a|
            @photo = @homes.photos.create!(:image => a, :home_id => @homes.id)
          end
          format.html { redirect_to @homes, notice: 'Home was successfully created.' }
          format.json { render :index, status: :created, location: @homes }
        else
          format.html { render :new }
          format.json { render json: @homes.errors, status: :unprocessable_entity }   
        end
      else
        flash[:error] = "Photos can't be blank!"
        format.html { render :new}
        format.json { render json: @homes.errors, status: :unprocessable_entity } 
      end

    end
	end

	def show
    @home = Home.find(params[:id])
	end

  def destroy
 
    @home = Home.find(params[:id])
    @home.destroy
  
    redirect_to :admin , notice: 'Home was successfully destroyed.'
  end

	def show_near_by_homes		
		respond_to do |format|
			homes = Home.near(params[:locat], 20)
			format.json { render json: homes.map{|f| HomesSerializer.new(f)}.to_json}
		end
	end

  def show_filter
    p params["price_min"]..params["price_max"]
    respond_to do |format|
      homes = Home.search([(params["price_min"].to_i)..(params["price_max"].to_i)], params["locat"],params["pets"],params["internet"],params["tv"],params["laundry"], params["heater"], params["parking"],params["air"])
      format.json { render json: homes.map{|f| HomesSerializer.new(f)}.to_json }
    end
  end


	private

	def home_params
    params.require(:home).permit(:title, :address, :host, :contact, :email, :website, :description, :rate, :min_stay , :pets, :bond ,:internet, :tv ,:laundry ,:heater ,:parking ,:air_cond,:h_type, photo: [:id, :home_id, :image])
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]
  before_filter :is_admin?

  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    if @photo.home.photos.count > 1
      @photo.destroy
      respond_to do |format|
        format.html { redirect_to admin_path, notice: 'Photo was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to admin_path, notice: 'Cant destroy a photo.' }
        format.json { head :no_content }
      end
    end
  end

  def homephoto
    @photo = Photo.all.where(home_id: params[:id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:home_id, :image)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/admin/index.html.erb
<table class="table table-hover" >
    <thead>
      <tr>
        <th>Image</th>
        <th>Address</th>
        <th>Price</th>
        <th>Description</th>
        <th>Created at</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody id="admin-table">
        <% if @homes.count < 1 %>
          <tr><td></td><td></td><td></td><td>No house to show</td><td></td><td></td><td></td></tr>
        <% end %>
        
    	<% for home in @homes %>
      <tr>
        <td>
            <a href="<%="/home/photos/#{home.id}"%>">
            <% if home.photos.exists? %>
                <%= image_tag(home.photos.first.image_url(:thumbnail), :width => 50, :height => 50)%></a>
            <% else %>
                No image
            <% end %>
        </td>
        <td><%= home.address %></td>
        <td><%= home.rate %></td>
        <td><%= home.description %></td>
        <td><%= time_ago_in_words(home.created_at) + " ago" %></td>

        <th><%= link_to "Show", { :controller => :homes, :action => :show ,:id => home.id }, { class: "btn btn-primary", style: "width: 100%;" } %></th>
        <th><a href="/homes/<%=home.id%>/edit" data-method="get" class="btn btn-info" style="width:100%">Edit</a></th>
        <th><a href="/homes/<%=home.id%>" data-method="delete" class="btn btn-danger" style="width:100%">Delete</a></th>
    	
      </tr>
      <% end %>
     
    </tbody>
 </table>

app/views/homes/_table_list.html.erb
<% for home in @homes %>

<a href="/homes/#{home.id}">
      <tr>
        <td>
        <% if home.photos.exists? %>
        	<%= image_tag(home.photos.first.image_url(:thumbnail), :width => 50, :height => 50)%>
        <% else %>
        	No Image
        <% end %>
        </td>
        <td><%= home.address %></td>
        <td><%= home.rate %></td>
        <td><%= home.description %></td>
      </tr>
      </a>
<% end %>

app/views/homes/index.html.erb
 <table class="table table-hover" >
    <thead>
      <tr>
        <th>Image</th>
        <th>Address</th>
        <th>Price</th>
        <th>Description</th>
      </tr>
    </thead>
    <tbody id="list-table">
      <%= render :partial => 'table_list', :object => @homes %>
    </tbody>
 </table>
 <script type="text/javascript">
   $('#submitfilter').click(function(){
              $('#myModal').modal('hide');
              var select = document.getElementById('select_type').value;
              console.log("type "+select);
              var price = document.getElementById('price_max').value;
              console.log("price "+price);
              var price_min = document.getElementById('price_min').value;
              console.log("price min "+price_min);
              var internet = document.getElementById('internet').checked;
              console.log("internet " + internet);
              var tv = document.getElementById('tv').checked;
              console.log("tv " + tv);
              var laundry = document.getElementById('laundry').checked;
              console.log("laundry " + laundry);
              var air_cond = document.getElementById('air_cond').checked;
              console.log("Air-Conditioning " + air_cond);
              var heater = document.getElementById('heater').checked;
              console.log("heater " + heater);
              var parking = document.getElementById('parking').checked;
              console.log("parking " + parking);
              var bond = document.getElementById('bond').checked;
              console.log("bond " + bond);
              var min_days_v;
              var min_days = document.getElementsByName('min_days');
              for (var i = 0; i < min_days.length; i++) {
                  if (min_days[i].checked) {
                      min_days_v = min_days[i].value;
                      break;
                  }else{

                  }
              }
              console.log("Min days " + min_days_v);
              var pets = document.getElementById('pets').checked;
              console.log("pets " + pets);

              $.ajax({
                 url: 'filter_homes/', 
                 data: {typ: select,price_max: price,price_min: price_min,internet: internet,tv: tv,laundry: laundry, air: air_cond, heater: heater, parking: parking, bond: bond,min_days: min_days_v,pets: pets},
                 error: function() {
                    console.log("Error!");
                 },
                 success: function(data) {
                    $('#list-table').html("");
                    for(i=0 ; i<data.length;i++){
                      console.log(data[i]);
                      rowdata = "<tr><td><img src="+data[i].image.url+" width=50 height=50></td><td>"+data[i].address+"</td><td>"+data[i].rate+"</td><td>"+data[i].description+"</td></tr>";
                      $('#list-table').append(rowdata);
                    }
                 },
                 type: 'GET'
              });
            });
 </script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShareHouse</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script type="text/javascript">
  window.heap=window.heap||[],heap.load=function(e,t){window.heap.appid=e,window.heap.config=t=t||{};var n=t.forceSSL||"https:"===document.location.protocol,a=document.createElement("script");a.type="text/javascript",a.async=!0,a.src=(n?"https:":"http:")+"//cdn.heapanalytics.com/js/heap-"+e+".js";var o=document.getElementsByTagName("script")[0];o.parentNode.insertBefore(a,o);for(var r=function(e){return function(){heap.push([e].concat(Array.prototype.slice.call(arguments,0)))}},p=["clearEventProperties","identify","setEventProperties","track","unsetEventProperty"],c=0;c<p.length;c++)heap[p[c]]=r(p[c])};
  heap.load("502944281");
</script>
</head>
<body>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>


<% if name.to_s == 'notice' %>
  <script type="text/javascript">alertify.success('<%= msg%>');</script>
  <%else%>
 <script type="text/javascript">alertify.error('<%= msg%>');</script>
<%end%>



  <% end %>
<% end %>
	<nav class="navbar navbar-default navbar-static-top" style="height: 60px; padding-top: 4px;">
	  <div class="container" style="">
	    <div class="navbar-header">
	      <p class="navbar-brand" ><a onclick="window.location.assign('/');" href="#" style="color: white ; text-decoration: none;"> Share House </a></p>
	    </div>

	    <ul class="nav navbar-nav navbar-right">
	    <% if user_signed_in?  and current_user.admin%>
	      <li>		

	      <button class="btn btn-primary" type="button" id="post-pad" onclick="window.location.assign('<%= "/admin" %>');" style="margin-right: 5px;margin-top: 9px;color: white;"><span class=""></span>Admin</button></li>
	      <%end%>
	        <li>			      
	      <button class="btn btn-primary" type="button" id="post-pad" onclick="window.location.assign('<%= new_home_path %>');" style="margin-right: 5px;margin-top: 9px;color: white;">Post space for free!</button></li>
	      <li>
	      
	      <li>
	      <% if user_signed_in? %>
      	      <button class="btn btn-primary" id="logout-button" onclick="destroy()" style="color: white;"><span class="glyphicon glyphicon-log-in" ></span> Logout</button>
	      <% else %>
	      <button class="btn btn-primary" id="login-button" onclick="window.location.assign('<%= new_user_session_path %>');" style="color: white;"><span class="glyphicon glyphicon-user" ></span> Login</button>
	      <% end %>
	      </li>

	    </ul>

	    <!-- <div class="col-md-3 col-md-offset-3">
	    	<form class="navbar-form" role="search">
				<div class="input-group">
				<input type="text" class="form-control" id="search-input" placeholder="Search Location" name="srch-term">
				<div class="input-group-btn">
				    <button class="btn btn-default" type="button"><i class="glyphicon glyphicon-search"></i></button>
				</div>
				</div>
			</form> 
	    </div> -->
	  </div>	
	</nav>

	<!-- <div class="navbar-collapse collapse navbar-inverse" id="simple-bar">
		<div class="container">
			<ul class="nav navbar-nav links" style="margin-left: -120px;">
		    	<li ><a href="/" id="show-map" >Map</a></li>
		    	<li><a href="<%= homes_path %>" id="show-list">List</a></li>
		    </ul>

		    <ul class="nav navbar-nav navbar-right" style="margin-top: 8px">
		      <li>			      <button class="btn btn-default" type="button" id="post-pad" onclick="window.location.assign('<%= new_home_path %>');" style="margin-right: 5px;"><span class="glyphicon glyphicon-plus"></span>&nbspPost</button></li>


			  <li><button type="button" class="btn btn-default" data-toggle="modal" data-target="#myModal">Filter</button>


				  <div class="modal fade" id="myModal" role="dialog">
				    <div class="modal-dialog">
				      <div class="modal-content">
				        <div class="modal-header">
				          <button type="button" class="close" data-dismiss="modal">&times;</button>
				          <h4 class="modal-title">Filter</h4>
				        </div>
				        <div class="modal-body">
			            	<form role="form">

							  <div class="form-group">
							    <label>Select home type</label>
							    <select class="form-control" id="select_type" >
							    	<option value="">Choose</option>
								    <option value="apartment">Apartment</option>
								    <option value="house">House</option>
								    <option value="other">Other</option>
								</select>
							  </div>
							  <div  class="form-group">
							  	<div class=" col-md-6">
							  		<input type="number" id="price_min" value="0" class="form-control" placeholder="Min Price" >
							  	</div>
							  	<div class=" col-md-6">
							  		<input type="number" id="price_max" value="10000" class="form-control" placeholder="Max Price" >
							  	</div>
							  	
							    
							  </div>

							  	<div class="form-group" >
							  		<label class="control-label"></label>
								  	<div class="checkbox">
									  <label><input type="checkbox" value="true" id="internet">Internet</label>
									</div>
									<div class="checkbox">
									  <label><input type="checkbox" value="true" id="tv">TV</label>
									</div>
									<div class="checkbox">
									  <label><input type="checkbox" value="true" id="laundry">Laundry</label>
									</div>
									<div class="checkbox">
									  <label><input type="checkbox" value="true" id="air_cond">Air-Conditioning</label>
									</div>
									<div class="checkbox">
									  <label><input type="checkbox" value="true" id="heater">Heater</label>
									</div>
									<div class="checkbox">
									  <label><input type="checkbox" value="true" id="parking">Parking</label>
									</div>
								</div>

								<div class="form-group">
							  		<label class="form-control">Minimum days stayed?</label>
									<div class="radio">
									  <label><input type="radio" name="min_days" value="1 day">1 day</label>
									</div>
									<div class="radio">
									  <label><input type="radio" name="min_days" value="2-6 days">2-6 days</label>
									</div>
									<div class="radio">
									  <label><input type="radio" name="min_days" value="1 week or more">1 week or more</label>
									</div>
								</div>

								<div class="form-group">
							  		<label class="form-control">Bond required?</label>
									<div class="checkbox">
									  <label><input type="checkbox" value="true" id="bond">Bond</label>
									</div>
								</div>

								<div class="form-group">
							  		<label class="form-control">House has pets?</label>
									<div class="checkbox">
									  <label><input type="checkbox" value="true" id="pets">Pets</label>
									</div>
								</div>
							</form>
				        </div>
				        <div class="modal-footer">
				          <button type="button" class="btn btn-success" id="submitfilter" onclick="filterhome()">Filter</button>
				          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				        </div>
				      </div>
				    </div>
				  </div>
			  </li>
		    </ul>
		</div>    
	</div>  --><!-- 
<style type="text/css">
	
</style>
<div class="full">
	<div id="sec-nav" class="container">
		<div class="row">
			<div class="col-md-4">
				<ul>
					<li class="active"><a href="">Map</a></li>
					<li><a href="">List</a></li>
				</ul>
			</div>
			<div class="col-md-4 col-md-offset-4 text-right button-post">
				<button class="btn btn-default" type="button" id="post-pad">Post a pad</button>
				<button class="btn btn-default" type="button" id="filter">Filters</button>
			</div>
		</div>
	</div>
	</div>
 -->
 <!-- <div id="map"></div>
 <div id="list" class="hidden"></div> -->
 <script type="text/javascript">
 	function destroy() {
      	$.ajax({
		   url: '<%= destroy_user_session_path %>', 
		   error: function() {
		      console.log("Error!");
		   },
		   success: function(data) {
		      location.reload();
		   },
		   type: 'DELETE'
		});
	}

	function filterhome(){
		$('#myModal').modal('hide');
/*		var select = document.getElementById('select_type').value;
		console.log("type "+select);
		var price = document.getElementById('price_max').value;
		console.log("price "+price);
		var internet = document.getElementById('internet').checked;
		console.log("internet " + internet);
		var tv = document.getElementById('tv').checked;
		console.log("tv " + tv);
		var laundry = document.getElementById('laundry').checked;
		console.log("laundry " + laundry);
		var air_cond = document.getElementById('air_cond').checked;
		console.log("Air-Conditioning " + air_cond);
		var heater = document.getElementById('heater').checked;
		console.log("heater " + heater);
		var parking = document.getElementById('parking').checked;
		console.log("parking " + parking);
		var bond = document.getElementById('bond').checked;
		console.log("bond " + bond);
		var min_days_v;
		var min_days = document.getElementsByName('min_days');
		for (var i = 0; i < min_days.length; i++) {
		    if (min_days[i].checked) {
		        min_days_v = min_days[i].value;
		        break;
		    }else{

		    }
		}
		console.log("Min days " + min_days_v);
		var pets = document.getElementById('pets').checked;
		console.log("pets " + pets);


		$.ajax({
		   url: 'filter_homes/', 
		   data: {typ: select,price: price,internet: internet,tv: tv,laundry: laundry, air: air_cond, heater: heater, parking: parking, bond: bond,min_days: min_days_v,pets: pets},
		   error: function() {
		      console.log("Error!");
		   },
		   success: function(data) {
		      for(i=0 ; i<data.length;i++){
                  console.log(data[i]);
                  position = new google.maps.LatLng(data[i].lat,data[i].long);
                  //img_sel = new google.maps.MarkerImage('images/p.png');
                  marker1 = new google.maps.Marker({
                    position: position,
                    map: map

                  });
                  infowindow = new google.maps.InfoWindow();
                }
		   },
		   type: 'GET'
		});*/

	}

	/*$("#show-list").click(function(){
		$("#show-map").removeClass('active');
    	$("#map").hide();
		$("#list").removeClass('hidden')
			.show()
    	$("#show-list").addClass('active');
    	window.location.assign('<%= homes_path %>');

	});

	
	$("#show-map").click(function(){
		$("#show-map").addClass('active');
    	$("#list").hide();
    	$("#map").show();
    	$("#show-list").removeClass('active');

	});*/

	
	
 </script>
 
	<%= yield %>

</body>
</html>

app/views/photos/_form.html.erb
<%= form_for(@photo) do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field hidden">
    <%= f.label :home_id %><br>
    <%= f.number_field :home_id %>
  </div>
  <div class="field">
    <%= f.file_field :image %>
  </div>
            
  <div class="actions" style="margin-top: 15px;">
    <%= f.submit %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<div class="shadowme">
			<h1 class="text-center">Editing Photo</h1>

			<%= render 'form' %>
			<br>
			<%= link_to 'Back', photos_path %>
		</div>
	</div>
</div>

app/views/photos/homephoto.html.erb
<p id="notice"><%= notice %></p>

<h1>Home Photos</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Home</th>
      <th>Title</th>
      <th>Image</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
      <% for photo in @photo %>
      <tr>
        <td><%= photo.home_id %></td>
        <td><%= photo.home.title %></td>
        <td><%= image_tag(photo.image_url(:thumbnail))%></td>
        <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
        <td><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
  </tbody>
</table>

app/views/photos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Photos</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Home</th>
      <th>Title</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @photos.each do |photo| %>
      <tr>
        <td><%= photo.home_id %></td>
        <td><%= Home.find(photo.home_id).title %></td>
        <td><%= image_tag(photo.image_url(:thumbnail))%></td>
        <td><%= link_to 'Show', photo %></td>
        <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
        <td><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/photos/new.html.erb
<h1>New Photo</h1>

<%= render 'form' %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Home:</strong>
  <%= @photo.home_id %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag(@photo.image_url(:thumbnail))%>
</p>

<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>